from building import *
import rtconfig

# get current directory
cwd     = GetCurrentDir()
# The set of source files associated with this SConscript file.
# micropython/py
src    = Glob('micropython/py/argcheck.c')
src    += Glob('micropython/py/asmarm.c')
src    += Glob('micropython/py/asmbase.c')
src    += Glob('micropython/py/asmthumb.c')
src    += Glob('micropython/py/asmx64.c')
src    += Glob('micropython/py/asmx86.c')
src    += Glob('micropython/py/asmxtensa.c')
src    += Glob('micropython/py/bc.c')
src    += Glob('micropython/py/binary.c')
src    += Glob('micropython/py/builtinevex.c')
src    += Glob('micropython/py/builtinhelp.c')
src    += Glob('micropython/py/builtinimport.c')
src    += Glob('micropython/py/compile.c')
src    += Glob('micropython/py/emitbc.c')
src    += Glob('micropython/py/emitcommon.c')
src    += Glob('micropython/py/emitglue.c')
src    += Glob('micropython/py/emitinlinethumb.c')
src    += Glob('micropython/py/emitinlinextensa.c')
src    += Glob('micropython/py/emitnarm.c')
src    += Glob('micropython/py/emitnative.c')
src    += Glob('micropython/py/emitnthumb.c')
src    += Glob('micropython/py/emitnx64.c')
src    += Glob('micropython/py/emitnx86.c')
src    += Glob('micropython/py/emitnxtensa.c')
src    += Glob('micropython/py/emitnxtensawin.c')
src    += Glob('micropython/py/formatfloat.c')
src    += Glob('micropython/py/frozenmod.c')
src    += Glob('micropython/py/gc.c')
src    += Glob('micropython/py/lexer.c')
src    += Glob('micropython/py/malloc.c')
src    += Glob('micropython/py/map.c')
src    += Glob('micropython/py/modarray.c')
src    += Glob('micropython/py/modbuiltins.c')
src    += Glob('micropython/py/modcmath.c')
src    += Glob('micropython/py/modcollections.c')
src    += Glob('micropython/py/modgc.c')
src    += Glob('micropython/py/modio.c')
src    += Glob('micropython/py/modmath.c')
src    += Glob('micropython/py/modmicropython.c')
src    += Glob('micropython/py/modstruct.c')
src    += Glob('micropython/py/modsys.c')
src    += Glob('micropython/py/modthread.c')
src    += Glob('micropython/py/moduerrno.c')
src    += Glob('micropython/py/mpprint.c')
src    += Glob('micropython/py/mpstate.c')
src    += Glob('micropython/py/mpz.c')
src    += Glob('micropython/py/nativeglue.c')
src    += Glob('micropython/py/nlr.c')
src    += Glob('micropython/py/nlrpowerpc.c')
src    += Glob('micropython/py/nlrsetjmp.c')
src    += Glob('micropython/py/nlrthumb.c')
src    += Glob('micropython/py/nlrx64.c')
src    += Glob('micropython/py/nlrx86.c')
src    += Glob('micropython/py/nlrxtensa.c')
src    += Glob('micropython/py/obj.c')
src    += Glob('micropython/py/objarray.c')
src    += Glob('micropython/py/objattrtuple.c')
src    += Glob('micropython/py/objbool.c')
src    += Glob('micropython/py/objboundmeth.c')
src    += Glob('micropython/py/objcell.c')
src    += Glob('micropython/py/objclosure.c')
src    += Glob('micropython/py/objcomplex.c')
src    += Glob('micropython/py/objdeque.c')
src    += Glob('micropython/py/objdict.c')
src    += Glob('micropython/py/objenumerate.c')
src    += Glob('micropython/py/objexcept.c')
src    += Glob('micropython/py/objfilter.c')
src    += Glob('micropython/py/objfloat.c')
src    += Glob('micropython/py/objfun.c')
src    += Glob('micropython/py/objgenerator.c')
src    += Glob('micropython/py/objgetitemiter.c')
src    += Glob('micropython/py/objint.c')
src    += Glob('micropython/py/objint_longlong.c')
src    += Glob('micropython/py/objint_mpz.c')
src    += Glob('micropython/py/objlist.c')
src    += Glob('micropython/py/objmap.c')
src    += Glob('micropython/py/objmodule.c')
src    += Glob('micropython/py/objnamedtuple.c')
src    += Glob('micropython/py/objnone.c')
src    += Glob('micropython/py/objobject.c')
src    += Glob('micropython/py/objpolyiter.c')
src    += Glob('micropython/py/objproperty.c')
src    += Glob('micropython/py/objrange.c')
src    += Glob('micropython/py/objreversed.c')
src    += Glob('micropython/py/objset.c')
src    += Glob('micropython/py/objsingleton.c')
src    += Glob('micropython/py/objslice.c')
src    += Glob('micropython/py/objstr.c')
src    += Glob('micropython/py/objstringio.c')
src    += Glob('micropython/py/objstrunicode.c')
src    += Glob('micropython/py/objtuple.c')
src    += Glob('micropython/py/objtype.c')
src    += Glob('micropython/py/objzip.c')
src    += Glob('micropython/py/opmethods.c')
src    += Glob('micropython/py/pairheap.c')
src    += Glob('micropython/py/parse.c')
src    += Glob('micropython/py/parsenum.c')
src    += Glob('micropython/py/parsenumbase.c')
src    += Glob('micropython/py/persistentcode.c')
src    += Glob('micropython/py/profile.c')
src    += Glob('micropython/py/pystack.c')
src    += Glob('micropython/py/qstr.c')
src    += Glob('micropython/py/reader.c')
src    += Glob('micropython/py/repl.c')
src    += Glob('micropython/py/ringbuf.c')
src    += Glob('micropython/py/runtime.c')
src    += Glob('micropython/py/runtime_utils.c')
src    += Glob('micropython/py/scheduler.c')
src    += Glob('micropython/py/scope.c')
src    += Glob('micropython/py/sequence.c')
src    += Glob('micropython/py/showbc.c')
src    += Glob('micropython/py/smallint.c')
src    += Glob('micropython/py/stackctrl.c')
src    += Glob('micropython/py/stream.c')
src    += Glob('micropython/py/unicode.c')
src    += Glob('micropython/py/vm.c')
src    += Glob('micropython/py/vstr.c')
src    += Glob('micropython/py/warning.c')

# micropython/shared/readline
src    += Glob('micropython/shared/readline/*.c')

# micropython/shared/runtime
#src    += Glob('micropython/shared/runtime/*.c')
src    += Glob('micropython/shared/runtime/interrupt_char.c')
src    += Glob('micropython/shared/runtime/mpirq.c')
src    += Glob('micropython/shared/runtime/printf.c')
src    += Glob('micropython/shared/runtime/pyexec.c')
src    += Glob('micropython/shared/runtime/stdout_helpers.c')
src    += Glob('micropython/shared/runtime/sys_stdio_mphal.c')

# micropython/extmod
#src    += Glob('micropython/extmod/*.c')
src    += Glob('micropython/extmod/machine_i2c.c')
src    += Glob('micropython/extmod/machine_mem.c')
src    += Glob('micropython/extmod/machine_pinbase.c')
src    += Glob('micropython/extmod/machine_pulse.c')
src    += Glob('micropython/extmod/machine_signal.c')
src    += Glob('micropython/extmod/machine_spi.c')
src    += Glob('micropython/extmod/modbtree.c')
src    += Glob('micropython/extmod/modframebuf.c')
src    += Glob('micropython/extmod/modonewire.c')
src    += Glob('micropython/extmod/modubinascii.c')
src    += Glob('micropython/extmod/moducryptolib.c')
src    += Glob('micropython/extmod/moductypes.c')
src    += Glob('micropython/extmod/moduhashlib.c')
src    += Glob('micropython/extmod/moduheapq.c')
src    += Glob('micropython/extmod/modujson.c')
src    += Glob('micropython/extmod/modurandom.c')
src    += Glob('micropython/extmod/modure.c')
src    += Glob('micropython/extmod/moduselect.c')
src    += Glob('micropython/extmod/modussl_axtls.c')
src    += Glob('micropython/extmod/modussl_mbedtls.c')
src    += Glob('micropython/extmod/modutimeq.c')
src    += Glob('micropython/extmod/moduwebsocket.c')
src    += Glob('micropython/extmod/moduzlib.c')
src    += Glob('micropython/extmod/modwebrepl.c')
src    += Glob('micropython/extmod/modwebsocket.c')
src    += Glob('micropython/extmod/uos_dupterm.c')
src    += Glob('micropython/extmod/utime_mphal.c')
src    += Glob('micropython/extmod/vfs.c')
src    += Glob('micropython/extmod/vfs_fat.c')
src    += Glob('micropython/extmod/vfs_fat_diskio.c')
src    += Glob('micropython/extmod/vfs_fat_file.c')
src    += Glob('micropython/extmod/vfs_posix.c')
src    += Glob('micropython/extmod/vfs_posix_file.c')
src    += Glob('micropython/extmod/vfs_reader.c')
src    += Glob('micropython/extmod/virtpin.c')

# ports/rt-thread
src    += Glob('micropython/ports/rt-thread/*.c')
src    += Glob('micropython/ports/rt-thread/native/*.c')
src    += Glob('micropython/ports/rt-thread/modules/*.c')
src    += Glob('micropython/ports/rt-thread/modules/machine/*.c')
src    += Glob('micropython/ports/rt-thread/modules/user/*.c')

# shared/netutils
src    += Glob('micropython/shared/netutils/netutils.c')

# shared/timeutils
src    += Glob('micropython/shared/timeutils/timeutils.c')

# drivers/bus
src    += Glob('micropython/drivers/bus/*.c')

path    = [cwd + '/micropython']
path   += [cwd + '/micropython/ports/rt-thread']
path   += [cwd + '/micropython/ports/rt-thread/modules']
path   += [cwd + '/micropython/ports/rt-thread/modules/machine']

LOCAL_CCFLAGS = ''

if rtconfig.CROSS_TOOL == 'gcc':
    LOCAL_CCFLAGS += ' -std=gnu99'
elif rtconfig.CROSS_TOOL == 'keil':
    LOCAL_CCFLAGS += ' --c99 --gnu'

group = DefineGroup('MicroPython', src, depend = ['PKG_USING_MICROPYTHON'], CPPPATH = path, LOCAL_CCFLAGS = LOCAL_CCFLAGS)

Return('group')
